### ISSUE TITLE
License & APK

### ISSUE THREAD

**Issue by IzzySoft** [zacharee/CellReader#1]
Just stumbled upon your app's repo and, using the packageId from the `build.gradle` also found it's listed at PlayStore. But what I could not find out is the license used – and how people without access to Google's walled garden could use your app. Did you already choose a F/LOSS license (see e.g. [SPDX](https://spdx.org/licenses/) and check those approved by OSI/FSF if still unsure)? And would you consider providing a signed release build e.g. attached to your releases?

**Comment by IzzySoft** [comment]
@zacharee any chance?

**Comment by zacharee** [comment]
Sorry, my notifications are all messed up on GitHub. I've added the MIT license. 

I'm probably not going to be providing builds here on GitHub, since the Play version is paid and I also have it available as a Patreon benefit.

**Comment by IzzySoft** [comment]
> Sorry, my notifications are all messed up on GitHub.

:see_no_evil: I know exactly what you mean. Happened to me more than once, too.

> I've added the MIT license.

Wonderful, thanks!

> I'm probably not going to be providing builds here on GitHub, since the Play version is paid and I also have it available as a Patreon benefit.

Oh, I wasn't aware of that. Maybe you could consider a "lite" variant (preferably also without Crashlytics/Firebase then, for the benefit of the F/LOSS folks)? Consider it a "promo action" then, drawing interest. In those big halls with millions of (often fake) apps, some good app got lost. But in the little gardens of F-Droid (my repo has about 1k apps, F-Droid's own about 4k) it would be discovered by some of those who'd otherwise have missed it. And some of them might consider "going pro" (provided they have a means to; most of us do not even have a Google account, for reasons).

That said, third variant: With your app under a free license, would you be opposed to a listing at [F-Droid](https://f-droid.org/)? F-Droid would build your app from source (while my repo just takes the APKs provided by the resp. devs) and either signs them with a key especially generated for it by F-Droid itself – or takes a corresponding APK signed by you if the build was "reproducible" (i.e. their APK is binary-identical to yours).

**Comment by zacharee** [comment]
I'm not sure if it's worth it for me to create a separate build config to exclude the GMS Wearable and Crashlytics libraries or disable certain features. This is mostly a hobby/personal project that I've made public. 

I get not wanting to use GMS on a device (and CellReader should be fully functional aside from the Wearable companion part without GMS), but the main reason it's on the Play Store is because I don't know of any other stores that let you post paid apps aside from the Amazon store which is pretty much unusable from a developer standpoint.

**Comment by IzzySoft** [comment]
Understood. Yes, Amazon Store would not be better at all (though [PlayStore can be a pain in the … behind](https://sylviavanos.nl/blog/2021/12/24/google_play_hell.html) as well). F-Droid as well as my repo only can show donation links; as we do not have any user accounts, we cannot track payment either. Of course you could have some license key to be entered into the app once obtained OTR (bank transfer, Patreon, whatever). But yes, that would be extra work to implement.

Well, we should get rid of money altogether and … yeah, dream on :see_no_evil:

OK, I won't press – I totally understand your point. I fully accept if you close the issue and chapter – though I still hope we find a way, and you maybe keep this issue to ponder about :wink: Whichever it will be: thanks for your support, and all the best for you personally and your project here!
