### ISSUE TITLE
Build error (with a possible fix)

### ISSUE THREAD

**Issue by AnonCYTO** [zacharee/CellReader#3]
hi, debug build errored from [./data/src/main/java/dev/zwander/cellreader/data/util/UpdatableTreeSet.kt](https://github.com/zacharee/CellReader/blob/7b80fc4d14813fa317a42e2ac8a2ccfdc955d152/data/src/main/java/dev/zwander/cellreader/data/util/UpdatableTreeSet.kt#L202) saying:
> Argument type mismatch: actual type is 'java.util.function.IntFunction<kotlin.Array<T>>' , but 'kotlin.Array<(out) T!>!' was expected.

so i just did this:
```kotlin
override fun <T : Any?> toArray(generator: IntFunction<Array<T>>): Array<T> {
    val array = generator.apply(wrapped.size)
    return wrapped.toArray(array)
}
```

and it built successfully with like 5 warnings but the app works so... `¯\_(ツ)_/¯`

**Comment by zacharee** [comment]
This should be fixed now.

**Comment by AnonCYTO** [comment]
just built and tested, can confirm its fixed. 🚀
